project_id = "jllvchazpscdduhceusb"

[functions.check-drug-interactions]
verify_jwt = false

[functions.health-insights]
verify_jwt = false

[functions.send-appointment-reminder]
verify_jwt = false

[functions.smart-diagnosis]
verify_jwt = false
